### ISSUE TITLE
Grid Daemon integration testing design

### ISSUE THREAD

**Issue by dplumb94** [hyperledger/grid#318]
Formalize the design for integration testing in the Grid daemon

**Comment by RyanLassigBanks** [comment]
The Grid daemon already has integration tests that use a Postgres database in the [routes module](https://github.com/hyperledger/grid/blob/104c7c84a28c33e4058e56e56d9e3d3cb80d86f3/daemon/src/rest_api/routes/mod.rs#L48). These tests already cover the REST API routes supplied by the daemon, but do not offer coverage for the `EventProcessor`, and require a postgres instance to store test data. 

As such, our strategy should be to replace the database seeding/set up functions like `populate_proposal_table` with the `EventProcessor` in order to test that component, and to replace the use of Postgres with Sqlite, so that the tests no longer require an external database. I've created [Issue #338](https://github.com/hyperledger/grid/issues/338) to track this work.
